remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: "Affordable Housing in NYC: Distribution and Availability Over Time"
description: "Trends and changes from 2011 to 2021, derived from US Census and NYC Open Data datasets"